### ISSUE TITLE
Feature?

### ISSUE THREAD

**Issue by deanbushmiller** [Cisco-Talos/Re2Pcap#3]

**Comment by deanbushmiller** [comment]
Setting SRC and DST for the pcap in the interface might be helpful instead of pulling from docker image my example "Running on http://172.17.0.2:5000/" My pcap files have 172.17.0.2 as both SRV & DST

**Comment by amit-raut** [comment]
Thank you for the feature request @deanbushmiller :)

I implemented to have SRC/DST IP to be 10.10.10.1 and 10.10.10.2 respectively [here](https://github.com/Cisco-Talos/Re2Pcap/blob/d8303916c3d0b2ec1180f2a5bdcb9dd76e1be4d3/Re2Pcap/Re2Pcap#L316)  but I removed that because of inconsistent behavior of `tcpprep` and `tcprewrite` :(

I created issue for it with appneta/tcpreplay [here](https://github.com/appneta/tcpreplay/issues/564)

I have another thought of doing this which I'll try to implement in next release, but in my opinion this should not be a problem for testing Snort or IDS signatures generated by Re2Pcap

Thank you,
Amit

**Comment by amit-raut** [comment]
Thank you for the recommendation. 🙂

With [c74eac7](https://github.com/Cisco-Talos/Re2Pcap/commit/c74eac724372c88b0be5879fa21bc957bf3b600f) I implemented following 

SRC IP: 10.10.10.1
DST IP: 172.17.0.2

If you need to update the DST IP please use `tcprewrite -D [172.17.0.2/32]:[<Required IP/CIDR>] -i in.pcap -o out.pcap` as mentioned [here](https://stackoverflow.com/questions/35038269/rewrite-pcap-destination-ip-with-tcprewrite) or you can use `tcpprep` or `tcprewrite` to set endpoints as mentioned [here](https://stackoverflow.com/questions/42283757/modify-ip-addresses-in-a-socks-capture-pcap).

I hope this helps.

Thank you,
Amit 
Cisco Talos
